# Generated by Django 2.0.5 on 2018-06-03 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20180529_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.CharField(default='Mój Blog', max_length=200),
        ),
    ]
