# Generated by Django 2.0.5 on 2018-06-03 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20180603_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogclass',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
